name: Mirror and run GitLab CI

on:
  push:
    branches: [2.x]
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/islandora"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "git.drupal.org"
        GITLAB_USERNAME: "project_34868_bot"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "34868"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
