name: Automated testing

on: [push]

jobs:
  call-testing-workflow:
    uses: digitalutsc/reusable_workflows/.github/workflows/ci-testing.yml@main
    with:
      module_name: citation_select
      composer_name: drupal/citation_select
      test_suite: null
