id: filehash_settings
label: File Hash settings
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - filehash_algos
    - filehash_dedupe
  source_module: filehash
process:
  algos: filehash_algos
  dedupe: filehash_dedupe
destination:
  plugin: config
  config_name: filehash.settings
